name = "Agnes"
license = "GPL-3.0"
licenselink = "https://github.com/dchucks/agnes-hugo-theme/blob/main/LICENSE"
description = 'Agnes is a Landing Page theme ported from the free HTML template created by <a href="https://onepagelove.com/agnes">Cruip</a>. The design is lovely and features an intro screenshot preview area, product/service feature list and ends with three-tier pricing table.'

# The home page of the theme, where the source can be found.
homepage = "https://github.com/dchucks/agnes-hugo-theme"

# If you have a running demo of the theme.
demosite = "https://agnes-hugo-sample-site.netlify.app/"

tags = ["Landing", "Light", "Company", "Minimal"]
features = ["Single Page Website", "Blazing Fast", "Easy to deply and configure"]

# If the theme has a single author
[author]
    name = "Debashish Chakrabarty"
    homepage = "https://www.debashish.com"
