baseURL = "http://example.org/"
languageCode = "en-us"
title = "Specy Network Website"
theme = "Agnes"
[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "Specy-Network"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
	TwitterURL = "https://twitter.com/podbharati"
	GoogleURL = "http://google.com"
	FacebookURL = "https://facebook.com/podbharati"
	GithubURL="https://github.com/specy-network"
		
[params.content]
	LeadTitle = "Automation Made Easy"
	LeadDescription = "A COSMOS Layer1 for verifiable low-code automation on multichains."
	ButtonFirstlyCaption = "Lunch App"
	ButtonFirstlyURL = "http://3.145.81.95:5173"
	ButtonSecondaryCaption = "Go to Docs"
	
	ButtonSecondaryURL = "https://specy-network.gitbook.io/specy-network/introduction/what-is-specy-network"

	ImageURL="images/main1.png"
	Logo= "images/specylogo.png"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Automation Programming Language"
	FeatureDescription = ""
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Verifiable Task Execution"
	FeatureDescription = ""
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Multi-chain Support"
	FeatureDescription = ""
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Open Framework"
	FeatureDescription = ""
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Friends"
	PricingRate = "27"	
	ButtonCaption = "Learn More"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	

[[params.pricing]]
	PricingTitle = "Limit Order"
	PricingRate = "97"
	ButtonCaption = "Coming Soon"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"		
	
[[params.pricing]]
	PricingTitle = "NFTs"
	PricingRate = "147"
	ButtonCaption = "Coming Soon"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"
	[[params.pricing.Features]]
		Description = "Lorem ipsum is common text"	

[[params.news]]
	NewsTitle="Won prizes in 2023 Wanxiang Hackathon"
	NewsDate="Q3 of 2023"
	NewsContent=""
[[params.news]]
	NewsTitle="Specy-Network project initiation"
	NewsDate="Q2 of 2023"
	NewsContent=""

	